pipeline:
  build:
    image: plugins/docker
    registry: docker.cloud1d.com
    repo: docker.cloud1d.com/asia-licytacje
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - 1.0.0
      - 1.0
      - latest
  ssh:
    image: appleboy/drone-ssh
    host: cloud1d.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - cd ~/sites/ && ./update.sh
