pipeline:
  build:
    image: plugins/docker
    registry: docker.beetlock.com
    repo: docker.beetlock.com/parcel-test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - 1.0.0
      - 1.0
      - latest
  ssh:
    image: appleboy/drone-ssh
    host: beetlock.com
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - cd /home/lukasz/traefik-server/parcel-test/ && ./parcel-test.sh
