version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  asia-licytacje:
    image: docker.beetlock.com/asia-licytacje
    labels:
      - traefik.backend=asia-licytacje
      - traefik.frontend.rule=Host:licytacje.wolnik.co
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
